# Generated by Django 3.2.9 on 2021-12-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_venue_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='owner',
            field=models.IntegerField(verbose_name='Venue Owner'),
        ),
    ]
